{% set name = "mmdet" %}
{% set version = "2.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmdetection/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f65b76447f7d2f8d1527b01233a1ec4a6b610cc1a433903f5f57ba7a03f6eb9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - pytorch
  run:
    - python >=3.7
    - numpy
    - pycocotools
    - six
    - terminaltables
    - mmcv-full
    - py-opencv
    - pytorch

test:
  imports:
    - mmdet
  requires:
    - pip
  commands:
    - pip check
    - python3 -c "import mmdet; print(mmdet.__version__)"

about:
  home: https://github.com/open-mmlab/mmdetection
  summary: OpenMMLab Detection Toolbox and Benchmark
  description: |
    MMDetection is an open source object detection toolbox based on PyTorch. It is a part of the OpenMMLab project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/open-mmlab/mmdetection

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
